apiVersion: apps/v1
kind: Deployment
metadata:
  name: face-representation-v1
  namespace: face
  labels:
    app: representation
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: representation
      version: v1
  template:
    metadata:
      labels:
        app: representation
        version: v1
    spec:
      serviceAccountName: face-account
      containers:
      - name: representation
        image: perhurb/face-representation:v1.0.0
        imagePullPolicy: IfNotPresent
        env:
        - name: FACE_RECOGNITION_SERVICE
          valueFrom:
            configMapKeyRef:
              name: face-env
              key: face-database-compute-service
        - name: FACE_RECOGNITION_PORT
          valueFrom:
            configMapKeyRef:
              name: face-env
              key: face-database-compute-port
        ports:
        - containerPort: 9080
        securityContext:
          runAsUser: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: face-representation
  namespace: face
  labels:
    app: representation
    service: face-representation
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: representation
