# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: face.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nface.proto\x12\x0brecognition\"\x1d\n\nRecRequest\x12\x0f\n\x07\x66\x65\x61ture\x18\x01 \x03(\x02\"\x1b\n\x0bRecResponse\x12\x0c\n\x04name\x18\x02 \x01(\t2`\n\x16\x46\x61\x63\x65RecognitionService\x12\x46\n\x0f\x46\x61\x63\x65Recognition\x12\x17.recognition.RecRequest\x1a\x18.recognition.RecResponse\"\x00\x42\x1dZ\x1bgithub.com/face/recognitionb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'face_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\033github.com/face/recognition'
  _RECREQUEST._serialized_start=27
  _RECREQUEST._serialized_end=56
  _RECRESPONSE._serialized_start=58
  _RECRESPONSE._serialized_end=85
  _FACERECOGNITIONSERVICE._serialized_start=87
  _FACERECOGNITIONSERVICE._serialized_end=183
# @@protoc_insertion_point(module_scope)
